export const schema = {
  type: "object",
  properties: {
    salutation: { type: "string" },
    firstName: { type: "string" },
    lastName: { type: "string" },
    company: { type: "string" },
    title: { type: "string" },
    website: { type: "string" },
    description: { type: "string" },
    leadStatus: { type: "string" },
    leadOwner: { type: "string" },
    phone: { type: "string" },
    email: { type: "string" },
    street: { type: "string" },
    postalCode: { type: "string" },
    city: { type: "string" },
    country: { type: "string" },
    state: { type: "string" },
    employeesNumber: { type: "string" },
    annualRevenue: { type: "string" },
    leadSource: { type: "string" },
    industry: { type: "string" },
  },
};
