export type AppTextFieldProps = {
  id: string;
  value?: string | number;
  label?: string | number;
  type?: "string" | "number";
  disabled?: boolean;
  readonly?: boolean;
  required?: boolean;
  options?: any;
  autofocus?: boolean;
  rows?: string | number;
  labelAlignment?: "top" | "left";
  multiline?: boolean;
  emptyValue?: string | null | undefined;
  onChange?: (string) => void;
  onClick?: () => void;
  onBlur?: (id, string) => void;
  onFocus?: (id, string) => void;
  inputProps?: any;
  errors?: null | JSX.Element;
  errorsList?: Array<any>;
  valid?: boolean;
  description?: string;
  startAdornment?: string | JSX.Element;
  showLabel?: boolean;
  fullWidth?: boolean;
  widthSize?: "xs" | "sm" | "md" | "lg";
  variant?: "filled" | "standard" | "outlined" | undefined;
  placeHolder?: string;
};
